### PR TITLE
Convert kebob-case to snake-case in attribute names

### PR DESCRIPTION
**Pull request by walterdavis**
We made this change to meet a requirement in an application. I feel that it could be useful for others who are ingesting XML that's out of their control.

### CODE REVIEW

**Comment by maik** [comment]
That seems to be a useful addition, but I am wondering, if we should better call it [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Special_case_styles)? That is, we should rename the kabobtosnakecase option to kebabtosnakecase and we should rename all variables and constants, too.

**Comment by walterdavis** [comment]
I agree. I can make that change and re-submit.

**Comment by maik** [comment]
That'd be great!

**Comment by walterdavis** [comment]
Ready for your review.

**Comment by maik** [comment]
Thank you very much! It looks good and I've adjusted a few other things in the meantime. Did you create any tests? If not, I'll write some.

**Comment by walterdavis** [comment]
No, sorry, no tests. It is working in production here, if that's any consolation.

**Pull request merged**
